#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit checks..."

# Run linters
npm run lint:sol
npm run prettier:check

# Run tests
npm test

echo "Pre-commit checks completed!"
